/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface Marketer {
  'principal' : Principal,
  'name' : string,
  'referralCount' : bigint,
}
export interface Student {
  'principal' : Principal,
  'name' : string,
  'enrolledCourses' : Array<string>,
}
export interface StudentApplication {
  'contactInfo' : string,
  'courseSelected' : string,
  'name' : string,
  'referredBy' : [] | [string],
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'enrollInCourse' : ActorMethod<[string], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllMarketers' : ActorMethod<[], Array<Marketer>>,
  'getAllStudentApplications' : ActorMethod<
    [],
    Array<[bigint, StudentApplication]>
  >,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEnrolledCourses' : ActorMethod<[Principal], Array<Course>>,
  'getMarketerStats' : ActorMethod<[Principal], [string, bigint]>,
  'getStudentApplication' : ActorMethod<[bigint], [] | [StudentApplication]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitStudentApplication' : ActorMethod<[StudentApplication], bigint>,
  'trackMarketerReferral' : ActorMethod<[], undefined>,
  'updateMarketerName' : ActorMethod<[string], undefined>,
  'updateStudentName' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];